FROM debian:bookworm

WORKDIR /app/assets

# 安装基础工具
RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*

# 拷贝二进制（如果你想从宿主机复制，也可以用 volumes 替代）
COPY ./app/assets/swagger-mcp /app/assets/swagger-mcp

# 添加执行权限
RUN chmod +x /app/assets/swagger-mcp

ENTRYPOINT ["/app/assets/swagger-mcp"]
